settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 7 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: '所有系统运行正常' # 'All Systems Operational'
  notAllmonitorsOperational: '并非所有系统都在运行' # 'Not All Systems Operational'
  monitorLabelOperational: '运行状态' # 'Operational'
  monitorLabelNotOperational: '非运行状态' # 'Not Operational'
  monitorLabelNoData: '无数据' # 'No data'
  dayInHistogramNoData: '无数据' # 'No data'
  dayInHistogramOperational: '正常' # 'All good'
  dayInHistogramNotOperational: '事件数' # ' incident(s)' # xx incident(s) recorded

monitors:
  - id: workers-cloudflare-openai-proxy # unique identifier
    name: api.openai.com-代理
    description: 'api.openai.com 代理' # default=empty
    url: 'https://openai-api.617000.xyz/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: gemini-proxy-617000-xyz
    name: gemini-proxy
    description: 'Vercel上Gemini的代理'
    url: 'https://gemini-proxy.617000.xyz/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: blog-cloudflare-com
    name: The Cloudflare Blog
    url: 'https://blog.cloudflare.com/'
    method: GET
    expectStatus: 200

  - id: jetbrains
    name: jetbrains 激活码
    description: '激活码'
    url: 'http://jb.zhoujian.serv00.net/'
    method: GET
    expectStatus: 200

  - id: bot-617000-NextChat
    name: NextChat
    description: 'NextChat'
    url: 'https://bot.617000.xyz/'
    method: GET
    expectStatus: 200
    
